name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'systemcodehead.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy DEV!
        
  build-hml:
    runs-on: ubuntu-latest
    environment:
      name: hml
      url: 'systemcodehead.com.br'      
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy HML!
        
  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'systemcodehead.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy PRD!    
      
      - name: Checkout files
        uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: alveselton/node-ci-cd
          tag_with_ref: true
          tag_with_sha: true
  
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files
        uses: actions/checkout@v2     
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --sizer s-1vcpu-256mb --region nyc1 --user-data-file deploy.sh --wait
